[package]
name = "forza"
version = "1.1.4"
authors = ["Maciej Małecki <me@mmalecki.com>"]

[dependencies]
timer = "0.1.6"
rustc-serialize = "0.3.21"
numbat = "0.3.0"
chrono = "0.2.25"
serde_json = "0.8.3"
libc = "0.2.18"
linux-stats = "0.1.0"
